### ISSUE TITLE
ecasound -i somefile.mp3 -o on OSX?

### ISSUE THREAD

**Issue by Xuuki** [skakri/ecasound#1]
how can I get an output on OSX if it doens't have alsa? what do I put on the end of the command ecasound -i somefile.mp3 -o ??

Also is this the correct place to leave questions? Like a forum? I'm struggling to find help for ecasound online?

Many thanks

Joel

**Comment by skakri** [comment]
Hi. This is just a mirror, try to get in touch with ecasound developers via mailing list (https://ecasound.seul.org/ecasound/mlists.php) or their issue tracker (https://sourceforge.net/p/ecasound/bugs/).
